CREATE TABLE "Mae_METADE_NOT_OTM" AS
SELECT * FROM "Mae"
LIMIT (SELECT COUNT(*) / 2 FROM "Mae");

CREATE TABLE "Mae_METADE_OTM" AS
SELECT * FROM "Mae"
LIMIT (SELECT COUNT(*) / 2 FROM "Mae");


CREATE TABLE "NascidoVivo_METADE_NOT_OTM" AS
SELECT * FROM "NascidoVivo"
LIMIT (SELECT COUNT(*) / 2 FROM "NascidoVivo");

CREATE TABLE "NascidoVivo_METADE_OTM" AS
SELECT * FROM "NascidoVivo"
LIMIT (SELECT COUNT(*) / 2 FROM "NascidoVivo");

CREATE TABLE "Registro_METADE_OTM" AS
SELECT * FROM "Registro"
LIMIT (SELECT COUNT(*) / 2 FROM "Registro");

CREATE TABLE "Registro_METADE_NOT_OTM" AS
SELECT * FROM "Registro"
LIMIT (SELECT COUNT(*) / 2 FROM "Registro");

CREATE INDEX id_metade 