CREATE VIEW "CONSOLIDA_OTM_V1"  AS 
SELECT a.id AS idnasc,
    b.id AS idmae,
    c.id AS idreg,
    a.ano_nasc,
    a."APGAR1",
    a."APGAR5",
    a."CODMUNNASC",
    a."LOCNASC",
    a."CODANOMAL",
    a."GESTACAO",
    a.contador,
    a."GRAVIDEZ",
    a."PARTO",
    a."CONSULTAS",
    a."DTNASC",
    a.data_nasc,
    a.dia_semana_nasc,
    a."HORANASC",
    a."SEXO",
    a."RACACOR",
    a."PESO",
    a."IDANOMAL",
    a."CONSPRENAT",
    a."MESPRENAT",
    a."TPAPRESENT",
    a."STTRABPART",
    a."STCESPARTO",
    a."TPNASCASSI",
    a."KOTELCHUCK",
    a."PARIDADE",
    a."nasc_CODIGO_UF",
    a.parto_prematuro,
    a."STDNNOVA",
    a."SEMAGESTAC",
    b."CODMUNNATU",
    b."CODMUNRES",
    b."IDADEMAE",
    b."ESTCIVMAE",
    b."ESCMAE",
    b."CODOCUPMAE",
    b."QTDFILVIVO",
    b."QTDFILMORT",
    b."NATURALMAE",
    b."CODUFNATU",
    b."RACACORMAE",
    b."DTNASCMAE",
    b."SERIESCMAE",
    b."ESCMAE2010",
    b."QTDGESTANT",
    b."QTDPARTNOR",
    b."QTDPARTCES",
    b."DTULTMENST",
    b."TPMETESTIM",
    b."ESCMAEAGR1",
    b."CODPAISRES",
    b."res_CODIGO_UF",
    c."ORIGEM",
    c."CODESTAB",
    c."DTCADASTRO",
    c."NUMEROLOTE",
    c."VERSAOSIST",
    c."DTRECEBIM",
    c."DIFDATA",
    c."DTRECORIGA",
    c."TPFUNCRESP",
    c."TPDOCRESP",
    c."DTDECLARAC",
    c."STDNEPIDEM",
    c."TPROBSON"
   FROM "NascidoVivo" a
     JOIN "Mae" b ON a.id = b.id
     JOIN "Registro" c ON b.id = c.id;

CREATE VIEW "CONSOLIDA_NOT_OTM_V1" AS 
 SELECT a.id AS idnasc,
    b.id AS idmae,
    c.id AS idreg,
    a.ano_nasc,
    a."APGAR1",
    a."APGAR5",
    a."CODMUNNASC",
    a."LOCNASC",
    a."CODANOMAL",
    a."GESTACAO",
    a.contador,
    a."GRAVIDEZ",
    a."PARTO",
    a."CONSULTAS",
    a."DTNASC",
    a.data_nasc,
    a.dia_semana_nasc,
    a."HORANASC",
    a."SEXO",
    a."RACACOR",
    a."PESO",
    a."IDANOMAL",
    a."CONSPRENAT",
    a."MESPRENAT",
    a."TPAPRESENT",
    a."STTRABPART",
    a."STCESPARTO",
    a."TPNASCASSI",
    a."KOTELCHUCK",
    a."PARIDADE",
    a."nasc_CODIGO_UF",
    a.parto_prematuro,
    a."STDNNOVA",
    a."SEMAGESTAC",
    b."CODMUNNATU",
    b."CODMUNRES",
    b."IDADEMAE",
    b."ESTCIVMAE",
    b."ESCMAE",
    b."CODOCUPMAE",
    b."QTDFILVIVO",
    b."QTDFILMORT",
    b."NATURALMAE",
    b."CODUFNATU",
    b."RACACORMAE",
    b."DTNASCMAE",
    b."SERIESCMAE",
    b."ESCMAE2010",
    b."QTDGESTANT",
    b."QTDPARTNOR",
    b."QTDPARTCES",
    b."DTULTMENST",
    b."TPMETESTIM",
    b."ESCMAEAGR1",
    b."CODPAISRES",
    b."res_CODIGO_UF",
    c."ORIGEM",
    c."CODESTAB",
    c."DTCADASTRO",
    c."NUMEROLOTE",
    c."VERSAOSIST",
    c."DTRECEBIM",
    c."DIFDATA",
    c."DTRECORIGA",
    c."TPFUNCRESP",
    c."TPDOCRESP",
    c."DTDECLARAC",
    c."STDNEPIDEM",
    c."TPROBSON"
   FROM "NascidoVivo_not_otm" a
     JOIN "Mae_not_otm" b ON a.id = b.id
     JOIN "Registro_not_otm" c ON b.id = c.id;